import { CSSProperties } from "react";
import { IThemeClasses } from "types/theme";

export interface IIconStaticProps {
  iconName:
    | "afterEffects"
    | "airbnb"
    | "apollo"
    | "auth0"
    | "axios"
    | "bamboo"
    | "basecamp"
    | "buildkite"
    | "chakra"
    | "coffeeScript"
    | "corelDraw"
    | "css"
    | "cssModules"
    | "cypress"
    | "docker"
    | "docpad"
    | "ember"
    | "express"
    | "figma"
    | "gallery"
    | "github"
    | "gitlab"
    | "graphQL"
    | "grunt"
    | "gulp"
    | "html"
    | "jenkins"
    | "jest"
    | "jira"
    | "jQuery"
    | "javaScript"
    | "less"
    | "link"
    | "nestJs"
    | "nextJs"
    | "nodeJs"
    | "phabricator"
    | "photoshop"
    | "prestashop"
    | "prisma"
    | "quire"
    | "qUnit"
    | "rubyOnRails"
    | "react"
    | "reactQuery"
    | "redmine"
    | "redux"
    | "rest"
    | "ruby"
    | "sass"
    | "sinatra"
    | "sketch"
    | "stash"
    | "styledComponents"
    | "tailwind"
    | "taskade"
    | "reactTestingLibrary"
    | "trello"
    | "typeScript"
    | "vite"
    | "webpack"
    | "websocket"
    | "windiCss"
    | "zeplin"
    | "calendar";
  style?: CSSProperties;
  themeClasses?: Pick<IThemeClasses, "height" | "overflow" | "width">;
}
