name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.8.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: build
        run: |
          npm install yarn -g
          yarn install
          yarn cache clean
          yarn build
        env:
          CI: true
