name: Build

on: [push]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: build
        run: |
          npm install yarn -g
          yarn install
          yarn cache clean
          yarn build
        env:
          CI: true
