name: End-to-end tests

on: [push]

jobs:
  end-to-end:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.11.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start:ci-e2e
          wait-on: "http://localhost:3000"
