name: End-to-end tests

on:
  pull_request:
    branches: [master]

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Use Node.js 18.2.0
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.2.0

      - name: Install dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        id: run_tests
        run: yarn playwright test 2> e2e_test.log || true
        env:
          CI: true

      - name: Save test log as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: e2e_test_log
          path: e2e_test.log

      - name: Download test log
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: e2e_test_log

      - name: Read test log
        if: always()
        run: |
          echo "E2E_TEST_LOG=$(cat e2e_test.log)" >> $GITHUB_ENV

      - name: Report success
        if: success()
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: e2e_execution
          pr_number: ${{ github.event.number }}
          message: |
            ### End-to-end tests passed ✅

      - name: Report failure with Test Log
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: e2e_execution
          pr_number: ${{ github.event.number }}
          message: |
            ## End-to-end tests failed 🚫

            ### Test Log

            ```
            ${{ env.E2E_TEST_LOG }}
            ```
