name: End-to-end tests

on:
  pull_request:
    branches: [master]
    
jobs:
  e2e:
    name: 'Playwright Tests - ${{ matrix.project }} - Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}'
    runs-on: macos-13

    strategy:
      fail-fast: false
      matrix:
        project: [webkit]
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        shardTotal: [10]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          CI: true

      - name: Save test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 30