name: End-to-end tests

on:
  pull_request:
    branches: [master]

jobs:
  e2e:
    permissions: write-all
    timeout-minutes: 60
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Use Node.js 18.2.0
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.2.0

      - name: Install dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: |
          yarn playwright test
        env:
          CI: true

      - name: Save test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
