name: End-to-end tests

on: [push]

jobs:
  end-to-end:

    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [14.11.0]
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000/portfolio'