name: End-to-end tests

on: [push]

jobs:
  end-to-end:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: test-end-to-end
        env:
          PORT: 3000
        uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn start -H 0.0.0.0 -p 3000
          wait-on: "http://0.0.0.0:3000"

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: cypress/snapshots/__diff_output__
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
