name: End-to-end tests

on:
  pull_request:
    branches: [master]

jobs:
  e2e:
    name: 'Playwright Tests - ${{ matrix.project }} - Shard ${{ matrix.shardIndex }} of ${{ matrix.shardTotal }}'
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        project: [webkit]
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        shardTotal: [10]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
    
      - name: Use Node.js 18.2.0
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.2.0

      - name: Install Docker
        run: |
          brew install --cask docker
          open -a Docker
          while (! docker stats --no-stream ); do
            # Docker takes a few seconds to initialize
            echo "Waiting for Docker to launch..."
            sleep 1
          done

      - name: Run Docker container
        id: docker
        run: |
          docker pull mcr.microsoft.com/playwright:v1.20.0-focal
          docker run -d -v $PWD:/work -w /work mcr.microsoft.com/playwright:v1.20.0-focal
          echo "DOCKER_ID=$(docker ps -q)" >> $GITHUB_ENV

      - name: Install dependencies
        run: docker exec -it ${{ env.DOCKER_ID }} yarn

      - name: Install Playwright Browsers
        run: docker exec -it ${{ env.DOCKER_ID }} yarn playwright install --with-deps

      - name: Run Playwright tests
        run: docker exec -it ${{ env.DOCKER_ID }} npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          CI: true

      - name: Save test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
