name: Unit tests, integration tests and lint

on:
  pull_request:
    branches: [master]

jobs:
  unit-integration-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Unit tests, integration tests and lint
        id: run_tests
        run: ./ci/scripts/run_tests_and_capture_logs.sh
        env:
          CI: true

      - name: Report failure reason
        uses: peter-evans/create-or-update-comment@v1
        if: steps.run_tests.outputs.test_exit_code != '0'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            ## Unit tests, integration tests and lint failure 🚫

            ### Lint Log

            ```
            ${{ steps.run_tests.outputs.lint_log }}
            ```

            ### Test Log

            ```
            ${{ steps.run_tests.outputs.test_log }}
            ```
          edit-mode: replace
