name: Unit tests, integration tests and lint

on:
  pull_request:
    branches: [master]

jobs:
  unit-integration-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Unit tests, integration tests and lint
        id: run_tests
        run: |
          npm install yarn -g
          yarn install
          yarn lint 2> lint.log
          lint_exit_code=$?
          yarn test 2> test.log
          test_exit_code=$?
          echo "Lint log and test log saved as artifacts."
          exit $((lint_exit_code | test_exit_code))

      - name: Save logs as artifacts
        if: always()
        id: save_logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            lint.log
            test.log

      - name: Download logs
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: logs
          path: logs/

      - name: List logs directory
        if: always()
        run: |
          ls logs

      - name: Set logs as output variables
        if: always()
        id: set_logs
        run: |
          echo "LINT_LOG<<EOF" >> $GITHUB_ENV
          cat logs/lint.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "TEST_LOG<<EOF" >> $GITHUB_ENV
          cat logs/test.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Report failure reason
        if: always()
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: execution
          pr_number: ${{ github.event.number }}
          message: |
            ${{ success() && '### Unit tests, integration tests and lint passed ✅' }}
            ${{ failure() && '## Unit tests, integration tests and lint failure 🚫' }}
            
            ${{ failure() && env.LINT_LOG != '' && join('\n### Lint Log\n\n```\n', env.LINT_LOG, '\n```\n') }}
            ${{ failure() && env.TEST_LOG != '' && join('\n### Test Log\n\n```\n', env.TEST_LOG, '\n```\n') }}
