name: Unit tests, integration tests and lint

on: [push]

jobs:
  unit-integration-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: test-unit
        run: |
          npm install yarn -g
          yarn install
          yarn lint
          yarn test
        env:
          CI: true
