name: Unit tests, integration tests and lint

on:
  pull_request:
    branches: [master]

jobs:
  unit-integration-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Test comment
      #   uses: thollander/actions-comment-pull-request@v2
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     comment_tag: execution
      #     pr_number: ${{ github.event.number }}
      #     message: 👋 Test comment!
  
      - name: Unit tests, integration tests and lint
        id: run_tests
        run: |
          npm install yarn -g
          yarn install
          yarn lint
          yarn test
        env:
          CI: true

      - name: Report failure reason
        uses: thollander/actions-comment-pull-request@v2
        if: failure()
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: execution
          pr_number: ${{ github.event.number }}
          message: |
            ## Unit tests, integration tests and lint failure 🚫

            ${{join(steps.run_tests.outputs.*, '\n')}}