name: Unit tests, integration tests and lint

on:
  pull_request:
    branches: [master]

jobs:
  unit-integration-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Unit tests, integration tests and lint
        id: run_tests
        run: |
          npm install yarn -g
          yarn install
          yarn lint 2>&1 | tee lint.log; test_exit_code=${PIPESTATUS[0]}
          yarn test 2>&1 | tee test.log; test_exit_code=$((test_exit_code | ${PIPESTATUS[0]}))
          echo "TEST_EXIT_CODE=$test_exit_code" >> $GITHUB_ENV
        env:
          CI: true

      - name: Read log files
        id: read_logs
        if: env.TEST_EXIT_CODE != '0'
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const lintLog = fs.readFileSync('lint.log', 'utf8');
            const testLog = fs.readFileSync('test.log', 'utf8');
            return {
              lint_log: lintLog,
              test_log: testLog
            };

      - name: Report failure reason
        uses: peter-evans/create-or-update-comment@v1
        if: env.TEST_EXIT_CODE != '0'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            ## Unit tests, integration tests and lint failure 🚫

            ### Lint Log

            ```
            ${{ steps.read_logs.outputs.lint_log }}
            ```

            ### Test Log

            ```
            ${{ steps.read_logs.outputs.test_log }}
            ```
          edit-mode: replace
