name: Unit tests, integration tests and lint

on:
  pull_request:
    branches: [master]

jobs:
  unit-integration-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Unit tests, integration tests and lint
        id: run_tests
        run: |
          npm install yarn -g
          yarn install
          yarn lint 2> lint.log
          lint_exit_code=$?
          yarn test 2> test.log
          test_exit_code=$?
          echo "Lint log and test log saved as artifacts."
          exit $((lint_exit_code | test_exit_code))

      - name: Report success
        if: success()
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: unit_integration_and_lint_execution
          pr_number: ${{ github.event.number }}
          message: |
            ### Unit tests, integration tests and lint passed ✅

      - name: Save logs as artifacts
        if: always()
        id: save_logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            lint.log
            test.log

      - name: Download logs
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: logs
          path: logs/

      - name: Set logs as output variables
        if: always()
        id: set_logs
        run: |
          echo "LINT_LOG<<EOF" >> $GITHUB_ENV
          cat logs/lint.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "TEST_LOG<<EOF" >> $GITHUB_ENV
          cat logs/test.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Report failure with Lint Log and Test Log
        if: failure() && env.LINT_LOG != '' && env.TEST_LOG != ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: unit_integration_and_lint_execution
          pr_number: ${{ github.event.number }}
          message: |
            ## Unit tests, integration tests and lint failure 🚫

            <details>
              <summary>Lint Logs</summary>

              ${{ env.LINT_LOG }}
            </details>

            <details>
              <summary>Test Logs</summary>

              ${{ env.TEST_LOG }}
            </details>

      - name: Report failure with Lint Log only
        if: failure() && env.LINT_LOG != '' && env.TEST_LOG == ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: unit_integration_and_lint_execution
          pr_number: ${{ github.event.number }}
          message: |
            ## Unit tests, integration tests and lint failure 🚫

            <details>
              <summary>Lint Logs</summary>

              ${{ env.LINT_LOG }}
            </details>

      - name: Report failure with Test Log only
        if: failure() && env.LINT_LOG == '' && env.TEST_LOG != ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: unit_integration_and_lint_execution
          pr_number: ${{ github.event.number }}
          message: |
            ## Unit tests, integration tests and lint failure 🚫

            <details>
              <summary>Test Logs</summary>

              ${{ env.TEST_LOG }}
            </details>

      - name: Report failure without logs
        if: failure() && env.LINT_LOG == '' && env.TEST_LOG == ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: unit_integration_and_lint_execution
          pr_number: ${{ github.event.number }}
          message: |
            ## Unit tests, integration tests and lint failure 🚫
