name: Update screenshots

on:
  pull_request:
    branches: [master]

jobs:
  update-screenshots:
    name: 'Update screenshots'
    runs-on: macos-13

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --update-snapshots
        env:
          CI: true

      - name: Save test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: end-to-end/specs/
          retention-days: 30